language: elixir

sudo: false

elixir:
  - 1.9

otp_release:
  - 21.3
  - 22.0

cache:
  directories:
    - _build
    - deps
    - priv/plts

env: MIX_ENV=test

script:
  - mix coveralls.travis
  - mix credo
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
